#!/usr/bin/env bash
# =============================================================================
# setup-server.sh — First-time server setup for the RDM stack
#
# Tested on: Ubuntu 22.04 LTS / Debian 12
# Run as root (or with sudo) on your server.
#
# What it does:
#   1. Installs Docker CE + Docker Compose v2
#   2. Creates the deploy user 'rdm' with limited privileges
#   3. Copies project files to /opt/rdm
#   4. Generates random secrets and writes .env
#   5. Issues a Let's Encrypt certificate via Certbot (standalone)
#   6. Starts the full stack with docker compose up -d
#   7. Prints the initial admin password and first-run checklist
# =============================================================================
set -euo pipefail

# ── Configuration — edit these before running ─────────────────────────────────
DOMAIN="${1:-}"                # e.g. rdm.yourcompany.com
CERTBOT_EMAIL="${2:-}"         # e.g. admin@yourcompany.com
DEPLOY_DIR="${3:-/opt/rdm}"   # where project files live on the server
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
GRAFANA_PASSWORD="${GRAFANA_PASSWORD:-}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

die()  { echo -e "${RED}ERROR: $*${NC}" >&2; exit 1; }
info() { echo -e "${GREEN}==> $*${NC}"; }
warn() { echo -e "${YELLOW}WARN: $*${NC}"; }

[[ $EUID -eq 0 ]] || die "Run as root: sudo bash setup-server.sh <domain> <email>"
[[ -n "$DOMAIN" ]] || die "Usage: $0 <domain> <certbot-email> [deploy-dir]"
[[ -n "$CERTBOT_EMAIL" ]] || die "Usage: $0 <domain> <certbot-email> [deploy-dir]"

# ── 1. Install Docker ─────────────────────────────────────────────────────────
info "Installing Docker CE..."
if ! command -v docker &>/dev/null; then
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg lsb-release
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
       https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
    systemctl enable --now docker
    info "Docker installed: $(docker --version)"
else
    info "Docker already installed: $(docker --version)"
fi

# ── 2. Create deploy user ─────────────────────────────────────────────────────
info "Creating deploy user 'rdm'..."
if ! id rdm &>/dev/null; then
    useradd -m -s /bin/bash rdm
    usermod -aG docker rdm
fi

# ── 3. Set up project directory ───────────────────────────────────────────────
info "Setting up project at $DEPLOY_DIR..."
mkdir -p "$DEPLOY_DIR"
chown rdm:rdm "$DEPLOY_DIR"

# If this script is being run from the project root, copy files
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
if [[ -f "$PROJECT_ROOT/infra/docker-compose.yml" ]]; then
    info "Copying project files to $DEPLOY_DIR..."
    rsync -a --exclude='.git' --exclude='node_modules' --exclude='build' \
          "$PROJECT_ROOT/" "$DEPLOY_DIR/"
    chown -R rdm:rdm "$DEPLOY_DIR"
else
    warn "Project files not found at $PROJECT_ROOT — copy them to $DEPLOY_DIR manually."
fi

# ── 4. Generate secrets and write .env ───────────────────────────────────────
ENV_FILE="$DEPLOY_DIR/.env"
info "Generating secrets and writing $ENV_FILE..."

gen_secret() { openssl rand -hex "${1:-32}"; }

if [[ -z "$POSTGRES_PASSWORD" ]]; then POSTGRES_PASSWORD=$(gen_secret 24); fi
if [[ -z "$GRAFANA_PASSWORD"   ]]; then GRAFANA_PASSWORD=$(gen_secret 16);  fi

JWT_SECRET=$(gen_secret 64)
DEVICE_TOKEN_SECRET=$(gen_secret 64)
TURN_SECRET=$(gen_secret 32)

cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-server.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")

JWT_SECRET=${JWT_SECRET}
DEVICE_TOKEN_SECRET=${DEVICE_TOKEN_SECRET}

POSTGRES_DB=rdm_db
POSTGRES_USER=rdm_user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql+asyncpg://rdm_user:${POSTGRES_PASSWORD}@postgres:5432/rdm_db

SIGNALING_PORT=4000
BACKEND_PORT=8000
FRONTEND_PORT=5173

TURN_DOMAIN=${DOMAIN}
TURN_SECRET=${TURN_SECRET}
TURN_PORT=3478

WS_MAX_CONNS_PER_IP=10
WS_PING_INTERVAL_MS=30000

DOMAIN=${DOMAIN}
CERTBOT_EMAIL=${CERTBOT_EMAIL}
CORS_ORIGINS=["https://${DOMAIN}"]

GRAFANA_PASSWORD=${GRAFANA_PASSWORD}

# Optional: set a bearer token to allow external Prometheus scrapers
METRICS_TOKEN=
EOF

chmod 600 "$ENV_FILE"
chown rdm:rdm "$ENV_FILE"
info ".env written (secrets are random — save them somewhere safe!)"

# ── 5. Obtain TLS certificate ─────────────────────────────────────────────────
info "Obtaining Let's Encrypt certificate for $DOMAIN..."
if [[ ! -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]]; then
    apt-get install -y -qq certbot
    # Temporarily stop anything on port 80
    if command -v nginx &>/dev/null; then systemctl stop nginx 2>/dev/null || true; fi
    certbot certonly --standalone \
        --non-interactive --agree-tos \
        --email "$CERTBOT_EMAIL" \
        --domain "$DOMAIN" \
        --domain "www.$DOMAIN"
    info "Certificate obtained."
else
    info "Certificate already exists — skipping."
fi

# ── 6. Configure Nginx env substitution ──────────────────────────────────────
# Nginx uses envsubst — make sure DOMAIN is exported in the compose env
grep -q "DOMAIN" "$ENV_FILE" || echo "DOMAIN=${DOMAIN}" >> "$ENV_FILE"

# ── 7. Start the stack ────────────────────────────────────────────────────────
info "Starting RDM stack..."
cd "$DEPLOY_DIR/infra"
docker compose --env-file "$ENV_FILE" pull --quiet
docker compose --env-file "$ENV_FILE" up -d --build

# Wait for backend health
info "Waiting for backend to be healthy..."
for i in $(seq 1 30); do
    if curl -sf "http://localhost:8000/health" &>/dev/null; then
        info "Backend is healthy."
        break
    fi
    sleep 2
done

# ── 8. Print summary ──────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}============================================================${NC}"
echo -e "${GREEN}  RDM stack is running!${NC}"
echo -e "${GREEN}============================================================${NC}"
echo ""
echo "  Dashboard:  https://${DOMAIN}"
echo "  Grafana:    https://${DOMAIN}/grafana  (admin / ${GRAFANA_PASSWORD})"
echo ""
echo "  Default RDM admin login:"
echo "    Username: admin"
echo "    Password: ChangeMe123!   ← CHANGE THIS IMMEDIATELY"
echo ""
echo "  Postgres password: ${POSTGRES_PASSWORD}"
echo "  JWT secret:        (see $ENV_FILE)"
echo ""
echo -e "${YELLOW}Post-setup checklist:${NC}"
echo "  1. Log in to the dashboard and change the admin password"
echo "  2. Issue device tokens for each PC:  POST /api/auth/device-token"
echo "  3. Run Enroll-RDMAgents.ps1 on your Windows admin machine"
echo "  4. Set up automatic certificate renewal (cron or systemd timer)"
echo "  5. Restrict /grafana/ to your office IP in nginx.conf"
echo "  6. Review and set METRICS_TOKEN in .env if Prometheus is external"
echo ""
echo "  Useful commands:"
echo "    cd $DEPLOY_DIR/infra"
echo "    docker compose logs -f backend-api"
echo "    docker compose restart backend-api"
echo "    docker compose down  (stops everything)"
echo ""
